
```{r}
library(DESeq2)
library(ggplot2)
library(readxl)
library(ggrepel)
library(limma)
library(pheatmap)
```


```{r}
set.seed(1066)
```

```{r}
plot_lib_sizes <- function(data) {
    df <- data.frame(lib.size = sort(colSums(data)))
        plot(ggplot(df, aes(x = reorder(rownames(df), lib.size), y = lib.size)) +
        geom_col() +
        ggtitle("Sorted library sizes") +
        theme(axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1)) +
        xlab(""))
}
```

```{r}
data <- read.csv("MyD88KODss_Counts.csv")
```

```{r}
# Remove rows with NA values
data <- na.omit(data)
```

```{r}
coldata <- data.frame(row.names = colnames(data)[2:ncol(data)])
```

```{r}
coldata$group  <-"Control-DSS"
coldata$group[grepl("A2", rownames(coldata))] <- "MyD88KO-Fib-DSS"
coldata$group[grepl("B2", rownames(coldata))] <- "MyD88KO-Fib-DSS"
```

```{r}
coldata$batch <-"Batch1"
coldata$batch[grepl("B", rownames(coldata))] <- "Batch2"
```

```{r}
counts <- data[, 2:ncol(data)]
counts <- lapply(counts, as.integer)
counts <- as.data.frame(counts)
counts <- as.matrix(counts)
rownames(counts) <- data$Gene
```

```{r}
plot_lib_sizes(counts)
```

```{r}
dds <- DESeqDataSetFromMatrix(counts, coldata, ~  group)
```

#Add gene info

```{r}
rowData(dds) <- data[, "Gene"]
```

```{r}
keep <- rowSums(counts(dds)) >= 11
dds <- dds[keep, ]
```

```{r}
sampleDists <- dist(t(assay(vst(dds, blind = FALSE))))
```
```{r}
pheatmap(as.matrix(sampleDists), cluster_cols = TRUE, cluster_rows = TRUE, show_colnames = FALSE)
```
```{r}
d <- plotPCA(vst(dds, blind=FALSE), intgroup = c("group"), returnData = TRUE)
percentVar <- round(100 * attr(d, "percentVar"))
ggplot(d, aes(x = PC1, y = PC2, color = group)) +
  geom_point() + 
  geom_label_repel(aes(label = colnames(dds)), show.legend = FALSE) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) + 
  coord_fixed()
```
```{r}
dds <- DESeqDataSetFromMatrix(counts, coldata, ~ batch + group)
```


```{r}
d <- plotPCA(vst(dds, blind = FALSE), intgroup = c("batch"), returnData = TRUE)
percentVar <- round(100 * attr(d, "percentVar"))
ggplot(d, aes(x = PC1, y = PC2, color = batch)) +
  geom_point() + 
  geom_label_repel(aes(label = colnames(dds)), show.legend = FALSE) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) + 
  coord_fixed()
```

#remove batch effect

```{r}
vsd <- vst(dds, blind = FALSE)
assay(vsd) <- limma::removeBatchEffect(assay(vsd), vsd$batch)
```

```{r}
d <- plotPCA(vsd, intgroup = c("group"), returnData = TRUE)
percentVar <- round(100 * attr(d, "percentVar"))
ggplot(d, aes(x = PC1, y = PC2, color = group)) +
  geom_point() + 
  geom_label_repel(aes(label = colnames(dds)), show.legend = FALSE) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) + 
  coord_fixed()
```


```{r}
rv <- rowVars(assay(vst(dds, blind = FALSE)))
# select the ntop genes by variance
select <- order(rv, decreasing=TRUE)[seq_len(min(500, length(rv)))]
# perform a PCA on the data in assay(x) for the selected genes
pca <- prcomp(t(assay(vst(dds, blind = FALSE))[select,]))
```

```{r}
idx <- order(abs(pca$rotation[, "PC1"]), decreasing = TRUE)[1:40]
pca$rotation[idx, "PC1"]
```
```{r}
write.csv(pca$rotation[idx, "PC1"], file = "DSS-PC1.csv")
```

```{r}
idx <- order(abs(pca$rotation[, "PC2"]), decreasing = TRUE)[1:40]
pca$rotation[idx, "PC2"]
```

```{r}
write.csv(pca$rotation[idx, "PC2"], file = "DSS-PC2.csv")
```


```{r}
custom_colors <- c("Control-DSS" = "steelblue", "MyD88KO-Fib-DSS" = "firebrick")
d2 <- plotPCA(vsd, intgroup = c("group"), returnData = TRUE)
percentVar <- round(100 * attr(d, "percentVar"))
ggplot(d2, aes(x = PC1, y = PC2, color = group)) +
  geom_point() + 
  geom_label_repel(aes(label = colnames(dds)), show.legend = FALSE) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) + 
  coord_fixed()+
   theme_bw()+
scale_color_manual(values = custom_colors)
```
```{r}
png("PCA_MyD88KO-Fib_DSS.png", width = 600, height = 400)
ggplot(d2, aes(x = PC1, y = PC2, color = group)) +
  geom_point() + 
  geom_label_repel(aes(label = colnames(dds)), show.legend = FALSE) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) + 
  coord_fixed()+
   theme_bw(base_size = 20) +
scale_color_manual(values = custom_colors)
```

```{r}
dds <- DESeq(dds, fitType = "local")
```

```{r}
ctrl.vs.ko <- as.data.frame(results(dds, contrast = c("group", "MyD88KO-Fib-DSS", "Control-DSS")))
ctrl.vs.ko <- ctrl.vs.ko[!is.na(ctrl.vs.ko$padj), ]
ctrl.vs.ko$sign <- ""
ctrl.vs.ko$sign[(ctrl.vs.ko$log2FoldChange < 0) & (ctrl.vs.ko$padj < 0.05)] <- "Downregulated"
ctrl.vs.ko$sign[(ctrl.vs.ko$log2FoldChange > 0) & (ctrl.vs.ko$padj < 0.05)] <- "Upregulated"
ctrl.vs.ko <- ctrl.vs.ko[order(ctrl.vs.ko$sign),]
```

```{r}
write.csv(ctrl.vs.ko, "DEGS_ctrl-vs-ko-dss.csv")
```

```{r}
highlightdwn<- ctrl.vs.ko[rownames(ctrl.vs.ko) %in% c( 
 
), ]

highlightup <- ctrl.vs.ko[rownames(ctrl.vs.ko) %in% c( "Spp1", "Il6st",  "Il1b", "Cxcl2", "Cxcr2", "S100a9", "S100a8", " Il1b ", "Lcn2 ", "Osmr", "Il1r1", "Timp3"
 
 
), ]
```

```{r}
ggplot(ctrl.vs.ko, aes(x = log2FoldChange, y = -log10(padj))) + 
  
  geom_point(aes(fill = sign, color = sign), 
             alpha = 0.2, 
             shape = 16,
             size = 1) + 
  scale_color_manual(values = c("gray", "steelblue", "firebrick"), name = "Significance", labels = c("Not significant", "Downregulated", "Upregulated")) +
  scale_fill_manual(values = c("gray", "steelblue", "firebrick"), name = "Significance", labels = c("Not significant", "Downregulated", "Upregulated")) + 
  

  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") + 
  geom_vline(xintercept = c(log2(0.5), log2(2)),
             linetype = "dashed") +
  geom_label_repel(data = highlightup,   
                   aes(label = rownames(highlightup)),
                   force = 2,
                   nudge_y = 3,
                   xlim = c(1, 6),
                   ylim = c(NA, NA)
                    ) +
  
   geom_label_repel(data = highlightdwn,   
                   aes(label = rownames(highlightdwn)),
                   force = 2,
                   nudge_y = 3,
                   xlim = c(-6, -1),
                   ylim = c(NA, NA)
                    ) +
  
  scale_x_continuous(breaks = c(seq(-4, 4, 2)),     
                     limits = c(-4.5, 4.5)) +
  labs(x = "log2(fold change)",
       y = "-log10(Padj)",
       colour = "Expression \nchange") +
  annotate("text", x = -3, y = 34, label = sprintf("Up in Control-DSS: %d", sum(ctrl.vs.ko$sign == "Downregulated"))) +
  annotate("text", x = 3, y = 34, label = sprintf("Up in MyD88-KO-DSS: %d", sum(ctrl.vs.ko$sign == "Upregulated"))) + 
  theme_bw(base_size = 14) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 
 
  
```



```{r}
pdf("ctrl-vs-ko-dss.pdf", width = 7, height = 4)
ggplot(ctrl.vs.ko, aes(x = log2FoldChange, y = -log10(pvalue))) + 
  
  geom_point(aes(fill = sign, color = sign), 
             alpha = 0.2, 
             shape = 16,
             size = 1) + 
  scale_color_manual(values = c("gray", "steelblue", "firebrick"), name = "Significance", labels = c("Not significant", "Downregulated", "Upregulated")) +
  scale_fill_manual(values = c("gray", "steelblue", "firebrick"), name = "Significance", labels = c("Not significant", "Downregulated", "Upregulated")) + 
  

  geom_hline(yintercept = -log10(0.05),
             linetype = "dashed") + 
  geom_vline(xintercept = c(log2(0.5), log2(2)),
             linetype = "dashed") +
  geom_label_repel(data = highlightup,   
                   aes(label = rownames(highlightup)),
                   force = 2,
                   nudge_y = 3,
                   xlim = c(1, 6),
                   ylim = c(NA, NA)
                    ) +
  
   geom_label_repel(data = highlightdwn,   
                   aes(label = rownames(highlightdwn)),
                   force = 2,
                   nudge_y = 3,
                   xlim = c(-6, -1),
                   ylim = c(NA, NA)
                    ) +
  
 scale_x_continuous(breaks = c(seq(-4, 4, 2)),     
                     limits = c(-4.5, 4.5)) +
  labs(x = "log2(fold change)",
       y = "-log10(Padj)",
       colour = "Expression \nchange") +
  annotate("text", x = -3, y = 34, label = sprintf("Up in Control-DSS: %d", sum(ctrl.vs.ko$sign == "Downregulated"))) +
  annotate("text", x = 3, y = 34, label = sprintf("Up in MyD88-KO-DSS: %d", sum(ctrl.vs.ko$sign == "Upregulated"))) + 
  theme_bw(base_size = 14) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, size= 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 
```

gseGO

```{r}
library(clusterProfiler)
library(msigdbr)
library(org.Mm.eg.db)
library(magrittr)

```

```{r}
# reading in data from deseq2
df = read.csv("DEGS_ctrl-vs-ko-dss.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list <- df$log2FoldChange

# name the vector
names(original_gene_list) <- df$X

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)
```

```{r}
gse <- gseGO(geneList=gene_list, 
             ont ="ALL", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 30, 
             maxGSSize = 1600, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Mm.eg.db, 
             pAdjustMethod = "BH")
```

```{r}
write.csv(gse, "gse-ctrl-vs-ko-dss.csv")
```

```{r}
require(DOSE)
dotplot(gse,
        showCategory=10, 
        split=".sign", 
        color = "p.adjust",
        
        
        label_format = 150, 
        
        ) + facet_grid(.~.sign) 

 categorys <- c("leukocyte chemotaxis", "extracellular matrix organization", "regulation of inflammatory response", "regulation of leukocyte activation", "myeloid leukocyte migration", "regulation of defense response", "interleukin-6 production", "leukocyte chemotaxis",  "mesenchymal cell differentiation", "regulation of peptidase activity", "response to bacterium", "cellular response to lipopolysaccharide")
    dotplot(gse, showCategory = categorys, split=".sign", 
        color = "p.adjust",
        font.size = 16,
        
        label_format = 160,
        
        ) + facet_grid(.~.sign) +
     theme_bw(base_size = 16) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, size= 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 

    
    

```

```{r}
pdf("gse-ctrl-vs-ko-dss.pdf", width = 7, height = 7)
require(DOSE)
dotplot(gse, showCategory=8, split=".sign") + facet_grid(.~.sign) +
  theme_bw(base_size = 15) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, size= 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 

#+
  #theme_bw(base_size = 10) +
          #ggtitle("GO pathway enrichment")
```

```{r}
pdf("gse-ctrl-vs-ko-dss-selected.pdf", width = 7, height = 4.5)
require(DOSE)
dotplot(gse, showCategory = categorys, split=".sign", 
        color = "p.adjust",
        font.size = 15,
        label_format = 160,
        
        ) + facet_grid(.~.sign) + theme_classic(base_size = 15) +
  theme_bw(base_size = 15) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, size= 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 
#+
  #theme_bw(base_size = 10) +
          #ggtitle("GO pathway enrichment")
```

```{r}

gseaplot(gse, by = "all", title = gse$Description[16], geneSetID = 3)
```

```{r}
library(clusterProfiler)
library(org.Mm.eg.db)
```


```{r}
# Convert gene IDs for gseKEGG function
# We will lose some genes here because not all IDs will be converted
ids<-bitr(names(original_gene_list), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)
 # remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]

# Create a new dataframe df2 which has only the genes which were successfully mapped using the bitr function above
df2 = df[df$X %in% dedup_ids$SYMBOL,]

# Create a new column in df2 with the corresponding ENTREZ IDs
df2$Y = dedup_ids$ENTREZID

# Create a vector of the gene unuiverse
kegg_gene_list <- df2$log2FoldChange

# Name vector with ENTREZ ids
names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)
set.seed(123456)

```


```{r}

kk2 <- gseKEGG(geneList     = kegg_gene_list,
               organism     = "mmu",
               keyType = "kegg",
  exponent = 1,
  minGSSize = 30,
  maxGSSize = 600,
  eps = 1e-10,
  pvalueCutoff = 0.05,
  pAdjustMethod = "none",
  verbose = TRUE,
  use_internal_data = FALSE,
  seed = FALSE,
  by = "fgsea"

)
```

```{r}

write.csv(kk2, "kegg_wt.vs.myd88ko-dss.csv")
```


```{r}
require(DOSE)
dotplot(kk2, 
        showCategory=10, 
        split=".sign", 
        color = "p.adjust",
        
        
        label_format = 80, 
        
        ) + facet_grid(.~.sign) 
```



```{r}
 categorys2 <- c("Cytokine-cytokine receptor interaction - Mus musculus (house mouse)", "Cell adhesion molecules - Mus musculus (house mouse)", "ECM-receptor interaction - Mus musculus (house mouse)", "Chemokine signaling pathway - Mus musculus (house mouse)", "Leukocyte transendothelial migration - Mus musculus (house mouse)", "Hematopoietic cell lineage - Mus musculus (house mouse)", "Complement and coagulation cascades - Mus musculus (house mouse)", "TNF signaling pathway - Mus musculus (house mouse)", "Chemokine signaling pathway - Mus musculus (house mouse)" )
 
 # Use sub to remove the substring
#cleaned_category <- gsub(" - Mus musculus \\(house mouse\\)", "", categorys2)



    dotplot(kk2, showCategory = categorys2, split=".sign", 
        color = "p.adjust",
       
        
        label_format = 120,
        
        ) + facet_grid(.~.sign) + theme_bw(base_size = 14) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, size= 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 

```


```{r}
pdf("KEGG-wt.vs.myd88ko-selected-dss.pdf", width = 7.5, height = 4)
  dotplot(kk2, showCategory = categorys2, split=".sign", 
        color = "p.adjust",
        font.size = 18,
        
        label_format = 120,
        
        ) + facet_grid(.~.sign) + theme_bw(base_size = 13) + # Select theme with a white background  
  theme(panel.border = element_rect(color = "black", fill = NA, size= 0.5),    
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) 

```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(immunedeconv)
library(tibble)
library(devtools)
library(pals)
library(readxl)

```


```{r}

df3 <- read.csv("MyD88KODSS_Counts.csv")
```


```{r}
df4 <- aggregate(. ~ Gene, data=df3, FUN=sum)

```


```{r}
# Extract the first column as row names
row.names(df4) <- df4$Gene
```

```{r}
df5 <- df4[, -c(1)]
row.names(df5) <- df4$Gene

```


```{r}
immunedeconv::deconvolute_mouse(df5, "mmcp_counter")
```

```{r}
write.csv(immunedeconv::deconvolute_mouse(df5, "mmcp_counter"), file = "deconvDSS.csv")
```


```{r}
res_mMCPcounter <- immunedeconv::deconvolute_mouse(df5, "mmcp_counter" )
```


```{r}
# Filter the data frame for the specified cell types
filtered_data <- res_mMCPcounter %>%
  filter(cell_type %in% c("B cell", "Monocyte", "Cancer associated fibroblast", "Endothelial cell", "Macrophage/Monocyte", "Neutrophil", "T cell", "Granulocyte-monocyte progenitor")) %>%
  mutate(cell_type = case_when(
    cell_type == "Cancer associated fibroblast" ~ "Activated Fibroblast",
    cell_type == "Macrophage/Monocyte" ~ "Activated Macrophage",
    cell_type == "Monocyte" ~ "Monocyte/Macrophage",
    TRUE ~ as.character(cell_type)
  ))


alphabet_palette <- c("#1f77b4", "#ff7f0e", "#2ca02c", "#8c564b", "#9467bd",  "#d62728" ,
                      "#e377c2", "#17becf")

# Plot using the "alphabet" palette
filtered_data  %>%
  gather(sample, score, -cell_type) %>%
  ggplot(aes(x = sample, y = score, color = cell_type)) +
  geom_point(size = 3) +
  facet_wrap(~cell_type, scales = "free_x", ncol = 4) +
  scale_color_manual(values = alphabet_palette) +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(), 
        text = element_text(size = 14)
        )

```